Name:           ros-jade-robot-self-filter
Version:        0.1.29
Release:        0%{?dist}
Summary:        ROS robot_self_filter package

Group:          Development/Libraries
License:        BSD
URL:            http://ros.org/wiki/robot_self_filter
Source0:        %{name}-%{version}.tar.gz

Requires:       assimp
Requires:       bullet-devel
Requires:       ros-jade-filters
Requires:       ros-jade-pcl-ros
Requires:       ros-jade-resource-retriever
Requires:       ros-jade-roscpp
Requires:       ros-jade-sensor-msgs
Requires:       ros-jade-tf
Requires:       ros-jade-urdf
Requires:       ros-jade-visualization-msgs
BuildRequires:  assimp-devel
BuildRequires:  bullet-devel
BuildRequires:  ros-jade-catkin
BuildRequires:  ros-jade-filters
BuildRequires:  ros-jade-pcl-ros
BuildRequires:  ros-jade-resource-retriever
BuildRequires:  ros-jade-roscpp
BuildRequires:  ros-jade-sensor-msgs
BuildRequires:  ros-jade-tf
BuildRequires:  ros-jade-urdf
BuildRequires:  ros-jade-visualization-msgs

%description
Filters the robot's body out of point clouds.

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/jade/setup.sh" ]; then . "/opt/ros/jade/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/jade" \
        -DCMAKE_PREFIX_PATH="/opt/ros/jade" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/jade/setup.sh" ]; then . "/opt/ros/jade/setup.sh"; fi
cd obj-%{_target_platform}
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/jade

%changelog
* Thu Dec 17 2015 Devon Ash <dash@clearpathrobotics.com> - 0.1.29-0
- Autogenerated by Bloom

